name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.extract_sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short commit hash
        id: extract_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.extract_sha.outputs.short_sha }} .
          if [ "${{ github.ref_name }}" = "master" ]; then
            docker tag ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.extract_sha.outputs.short_sha }} ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          fi

      - name: Push Docker image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.extract_sha.outputs.short_sha }}
          if [ "${{ github.ref_name }}" = "master" ]; then
            docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          fi

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull Docker image
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.build.outputs.short_sha }}

      - name: Run tests in Docker container
        run: |
          docker run --rm -e RUN_MODE="test" ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.build.outputs.short_sha }}
